service: shortener

plugins:
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-offline #needs to be last in the list

useDotenv: true
configValidationMode: warn

package:
  individually: false
  excludeDevDependencies: true
  patterns:
    - node_modules/**
    - src/**
    - '!.github/**'
    - '!.vscode/**'
    - '!coverage/**'
    - '!resources/**'
    - '!test/**'
    - '!.eslintrc.json'
    - '!.gitignore'
    - '!.nvmrc'
    - '!jest.config.js'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - '!serverless.yml'

provider:
  name: aws
  architecture: arm64
  region: ${opt:region}
  stage: ${opt:stage}
  runtime: nodejs18.x
  versionFunctions: true
  logRetentionInDays: 3
  timeout: 30
  stackName: serverless-${self:service}-${self:provider.stage}
  memorySize: 128
  tracing:
    apiGateway: true
  apiGateway:
    apiKeys: ${file(./resources/serverless.${self:provider.stage}.yml):apiGateway.apiKeys, ''}
    apiKeySourceType: HEADER
    disableDefaultEndpoint: true
  stackTags:
    Name: ${self:service}
  deploymentBucket:
    name: algum-s3-${self:provider.stage}-deployment
  environment: ${file(./resources/serverless.${self:provider.stage}.yml):environment}
  iam: ${file(./resources/serverless.${self:provider.stage}.yml):provider.iam, ''}
  logs:
    restApi:
      accessLogging: false
      executionLogging: false

functions:
  redirect:
    description: redirects hash to given url
    handler: src/handler.redirect
    events:
      - http:
          path: /{id}
          method: get
          cors: true
          private: false

resources: ${file(./resources/serverless.${self:provider.stage}.yml):resources, ''}

custom:
  dynamodb:
    stages:
      - local
    start:
      seed: true
      migrate: true
    seed:
      domain:
        sources:
          - table: Shortener
            sources: [./resources/db/shorts.json]
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  customDomain:
    enabled: true
    domainName: ${self:service}.${self:provider.stage}.seudominio.com.br
    stage: ${self:provider.stage}
    createRoute53Record: false
    basePath: ''